### PR TITLE
Add MathiasKoch to maintainer list

### PR DESCRIPTION
**Pull request by MathiasKoch**
As with Ryan in #10, i was approached by @eldruin about helping out with supporting `embedded-nal`, which i of course can spare some time for.

This PR adds myself to the list of maintainers in REC.

Of relevant stuff about myself, i can say that we are running embedded rust IoT devices in production at my workplace, developed by me. 

We have a stack making use of a larger number of projects we have OS'ed, a lot of which is still WIP, including:
- https://github.com/BlackbirdHQ/atat/
- https://github.com/BlackbirdHQ/ublox-cellular-rs/ 
- https://github.com/BlackbirdHQ/ublox-short-range-rs/
- https://github.com/BlackbirdHQ/mqttrust/
- https://github.com/BlackbirdHQ/rustot/
- https://github.com/BlackbirdHQ/defmt-persist
- https://github.com/BlackbirdHQ/at-cryptoauth-rs

Other than that i am also an active contributor and maintainer of the HAL we are using: https://github.com/stm32-rs/stm32l4xx-hal

### CODE REVIEW

**Review by eldruin — APPROVED** [review]
I believe @MathiasKoch is doing excellent work in lots of places and as we see, actively pushing open-source embedded Rust forward.
In the REC he has been contributing not only to `embedded-nal` but also to `serde-json-core`.
I would be happy to have him as a member of the REC.

Opinions @rust-embedded-community/all ?

**Review by Disasm — APPROVED** [review]

**Review by thejpster — APPROVED** [review]

**Comment by eldruin** [comment]
@MathiasKoch Could you rebase this?

**Comment by MathiasKoch** [comment]
@eldruin Done :+1:

**Review by jamesmunns — APPROVED** [review]
:+1:

**Comment by eldruin** [comment]
And consensus again. Thanks everyone and welcome @MathiasKoch!

**Pull request merged**
